
package interfaz;

import Clases.ClienteParticular;
import GestionClases.GestionRegistroClienteParticular;


public class PantallaRegistros extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla1 /constructor
     */
    public PantallaRegistros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreRegistro = new javax.swing.JLabel();
        textNombreRegistro = new javax.swing.JTextField();
        nombreRegistro1 = new javax.swing.JLabel();
        claveRegistro = new javax.swing.JLabel();
        textCorreoRegistro = new javax.swing.JTextField();
        botonRegistrarme = new javax.swing.JButton();
        correoRegistro = new javax.swing.JLabel();
        textClaveRegistro = new javax.swing.JTextField();
        dniRegistro = new javax.swing.JLabel();
        txtDniRegistro = new javax.swing.JTextField();
        telefonoRegistro = new javax.swing.JLabel();
        textTelefonoRegistro = new javax.swing.JTextField();
        botonYaTengoCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreRegistro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nombreRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreRegistro.setText("Registro");

        textNombreRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreRegistroActionPerformed(evt);
            }
        });

        nombreRegistro1.setText("Nombre:");

        claveRegistro.setText("Clave:");

        textCorreoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCorreoRegistroActionPerformed(evt);
            }
        });

        botonRegistrarme.setText("Registrarme");
        botonRegistrarme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarmeMouseClicked(evt);
            }
        });
        botonRegistrarme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarmeActionPerformed(evt);
            }
        });

        correoRegistro.setText("Correo:");

        textClaveRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textClaveRegistroActionPerformed(evt);
            }
        });

        dniRegistro.setText("DNI:");

        txtDniRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniRegistroActionPerformed(evt);
            }
        });

        telefonoRegistro.setText("Teléfono:");

        textTelefonoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTelefonoRegistroActionPerformed(evt);
            }
        });

        botonYaTengoCuenta.setText("Ya tengo cuenta...");
        botonYaTengoCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonYaTengoCuentaMouseClicked(evt);
            }
        });
        botonYaTengoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonYaTengoCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(nombreRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dniRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDniRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telefonoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(botonRegistrarme)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botonYaTengoCuenta))
                                        .addComponent(textTelefonoRegistro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombreRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNombreRegistro)
                                    .addComponent(claveRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textCorreoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(textClaveRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreRegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNombreRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCorreoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(claveRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(textClaveRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dniRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtDniRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(textTelefonoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegistrarme)
                    .addComponent(botonYaTengoCuenta))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreRegistroActionPerformed
        
    }//GEN-LAST:event_textNombreRegistroActionPerformed

    private void textCorreoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCorreoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCorreoRegistroActionPerformed

    private void botonRegistrarmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarmeActionPerformed
        
    }//GEN-LAST:event_botonRegistrarmeActionPerformed

    private void textClaveRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textClaveRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textClaveRegistroActionPerformed

    private void txtDniRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniRegistroActionPerformed

    private void textTelefonoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTelefonoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTelefonoRegistroActionPerformed

    private void botonYaTengoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonYaTengoCuentaActionPerformed
        
    }//GEN-LAST:event_botonYaTengoCuentaActionPerformed

    private void botonYaTengoCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonYaTengoCuentaMouseClicked
        PantallaSesion boton = new PantallaSesion();
        boton.setVisible(true);
        this.dispose();
        boton.setLocationRelativeTo(null);
        
        
    }//GEN-LAST:event_botonYaTengoCuentaMouseClicked

    private void botonRegistrarmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarmeMouseClicked
        //guardado en todas las variables
        
        
        String textoNombreRegistros = new String();
        String textoCorreoRegistros = new String();
        String textoClaveRegistros = new String();
        String textoDniRegistros = new String();
        String textoTelRegistros = new String();
        

        textoNombreRegistros = textNombreRegistro.getText();
        textoCorreoRegistros = textCorreoRegistro.getText();
        textoClaveRegistros = textClaveRegistro.getText();
        textoDniRegistros = txtDniRegistro.getText();
        textoTelRegistros = textTelefonoRegistro.getText();
              
        GestionRegistroClienteParticular gestionpartnew = new GestionRegistroClienteParticular();
        gestionpartnew.registrarClienteParticular(false, textoCorreoRegistros, textoClaveRegistros, textoNombreRegistros,  textoDniRegistros, textoTelRegistros);
        //vip false al principio
        
        
        
    }//GEN-LAST:event_botonRegistrarmeMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistrarme;
    private javax.swing.JButton botonYaTengoCuenta;
    private javax.swing.JLabel claveRegistro;
    private javax.swing.JLabel correoRegistro;
    private javax.swing.JLabel dniRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreRegistro;
    private javax.swing.JLabel nombreRegistro1;
    private javax.swing.JLabel telefonoRegistro;
    private javax.swing.JTextField textClaveRegistro;
    private javax.swing.JTextField textCorreoRegistro;
    private javax.swing.JTextField textNombreRegistro;
    private javax.swing.JTextField textTelefonoRegistro;
    private javax.swing.JTextField txtDniRegistro;
    // End of variables declaration//GEN-END:variables
}
